name: "Package Helm Chart"
description: "Packages a Helm chart with dynamic versioning and pushes to GHCR."
inputs:
  github-token:
    description: "GitHub Token for authentication"
    required: true
  path:
    description: "Path to the helm chart"
    required: true
    default: "."
  version-override:
    description: "Version to force in Chart.yaml"
    required: false
  validate_templates:
    description: "Run helm lint and template validation (handled inside script currently? logic removed in rewrite request but good to keep if compatible, user omitted it in requirements listing)"
    required: false
    default: "true"

outputs:
  chart-archive:
    description: "The .tgz file name"
    value: ${{ steps.package.outputs.chart-archive }}
  image:
    description: "Full OCI reference with digest"
    value: ${{ steps.package.outputs.image }}
  package:
    description: "Package path (repo-name/helm/chart-name)"
    value: ${{ steps.package.outputs.package }}
  version:
    description: "The final version of the chart (calculated or override)"
    value: ${{ steps.package.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Validate Templates
      if: inputs.validate_templates == 'true'
      shell: bash
      run: |
        echo "Running validation..."
        helm lint "${{ inputs.path }}"
        helm template "${{ inputs.path }}" > /dev/null

    - name: Package & Push Helm Chart
      id: package
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        chmod +x ${{ github.action_path }}/scripts/package-helm.sh

        # Build arguments string
        ARGS=""
        ARGS="$ARGS -p ${{ inputs.path }}"
        ARGS="$ARGS -t ${{ inputs.github-token }}"

        if [ -n "${{ inputs.version-override }}" ]; then
          ARGS="$ARGS -v ${{ inputs.version-override }}"
        fi

        ${{ github.action_path }}/scripts/package-helm.sh $ARGS

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-chart-archive
        path: ${{ inputs.path }}/${{ steps.package.outputs.chart-archive }}
        retention-days: 1

    - name: Delete Old Package Versions
      uses: actions/delete-package-versions@v5
      continue-on-error: true # Package might not exist yet on first run
      with:
        package-name: "base-k8s-chart"
        package-type: "container"
        min-versions-to-keep: 5
        delete-only-untagged-versions: "true"
        token: ${{ inputs.github-token }}
